site_name: My Docs

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deeppurple
      accent: deeppurple
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode

  language: fr
  icon:
    repo: fontawesome/brands/git-alt


plugins:
  - mkdocstrings

nav:
  - Accueil: index.md
  - API Reference: api.md
