# Generated by Django 4.2.2 on 2023-07-02 21:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("article", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="type",
        ),
    ]
