name: Setup project
description: Setup Python and Poetry
runs:
  using: composite
  steps:
    - name: Set up python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Load cached Poetry installation
      id: cached-poetry
      uses: actions/cache@v3
      with:
        path: ~/.local
        key: poetry-0  # increment to reset cache

    - name: Install Poetry
      if: steps.cached-poetry.outputs.cache-hit != 'true'
      shell: bash
      run: curl -sSL https://install.python-poetry.org | python3 -

    - name: Check pyproject.toml syntax
      shell: bash
      run: poetry check

    - name: Load cached dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pypoetry
        key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
        restore-keys: |
          ${{ runner.os }}-poetry-

    - name: Install dependencies
      run: poetry install
      shell: bash